name: chat_app
description: A cross-platform chat application

# 版本号遵循语义化版本规范 (https://semver.org/)
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI相关
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  lottie: ^2.3.2
  photo_view: ^0.14.0
  image_picker: ^0.8.7+5
  flutter_quill: ^8.5.0
  emoji_picker_flutter: ^1.5.4
  grouped_list: ^5.1.2
  azlistview: ^2.0.0
  badges: ^3.1.2

  # 状态管理
  provider: ^6.0.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

  # 路由
  go_router: ^10.1.2

  # 网络相关
  dio: ^5.1.2
  web_socket_channel: ^2.4.0
  connectivity_plus: ^4.0.1
  http: ^0.13.6

  # 本地存储
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15

  # 多媒体
  video_player: ^2.6.1
  just_audio: ^0.9.33
  camera: ^0.10.5
  screenshot: ^2.1.0
  record: ^4.4.4

  # 工具类
  intl: ^0.20.2
  logger: ^1.3.0
  uuid: ^3.0.7
  timeago: ^3.4.0
  url_launcher: ^6.1.11
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2
  permission_handler: ^10.2.0
  flutter_secure_storage: ^8.0.0
  crypto: ^3.0.3
  yaml: ^3.1.2

  # 推送通知
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  flutter_local_notifications: ^14.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  mockito: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

# 国际化配置
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/config/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  main_locale: zh
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated